import type { Metadata } from "next";
import "@/styles/global.css";
import { TanstackProvider } from "../components/tanstack-provider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";

export const metadata: Metadata = {
    title: "Hipaa",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <TanstackProvider>
                    <AppRouterCacheProvider>
                        <ThemeProvider theme={theme}>{children}</ThemeProvider>
                    </AppRouterCacheProvider>
                </TanstackProvider>
            </body>
        </html>
    );
}
